### ISSUE TITLE
Is this extension active?

### ISSUE THREAD

**Issue by jcvegan** [MohammedAldosari/json-translations-manager#36]
Hi, I would like to know if this extension is active or it is discontinued as the latest changes are from 2 years ago

**Comment by MohammedAldosari** [comment]
Dear @jcvegan  

Apologies for the delayed response. As the sole developer on this project, I'm dedicated to ensuring its smooth operation to the best of my abilities. Currently, the extension is functioning without any reported issues. However, if you encounter any problems or have suggestions for improvement, please feel free to share them, and I'll do my best to address them.

**Comment by MohammedAldosari** [comment]
Dear @jcvegan 

A new version has been released with some bug fixes if you need any support in this extension please open an issue in order to fix it 

> If you find this extension helpful, please take a moment to rate it, leave a review, and spread it among developers and on social media.
