### ISSUE TITLE
Move existing translation under another nested object

### ISSUE THREAD

**Issue by paul2t** [MohammedAldosari/json-translations-manager#37]
Changing the name of a translation from `name` to `nested.name` does not put `name` under `nested`.

**Comment by MohammedAldosari** [comment]
Dear @paul2t  ,

Can you please elaborate more?

**Comment by paul2t** [comment]
Thanks for the reply. Sorry for not being specific enough.
Here are the steps to reproduce:
1. Click on the `+` button to add a new translation.
2. Give it any key name. Let's says `test`.
3. Give it a value. Let's say `value`.
4. Click on `Save`
Here is what the json file will look like:
```json
{
  "test": "value"
}
```
6. Click on the `Rename` button of this translation (the pen icon).
7. Give it a new nested key name. Let's say `group.test`
The key in the json file will be:
```json
{
  "group.test": "value"
}
```
Instead of:
```json
{
  "group": {
    "test": "value"
  }
}
```
If you directly create a new translation by directly giving it the key `group.test`, you will get the correct json above.

**Comment by MohammedAldosari** [comment]
clear I will work to resolve it ASAP

**Comment by MohammedAldosari** [comment]
This issue is fixed and I have updated the extension in the marketplace please check it.


> If you find this extension helpful, please take a moment to rate it, leave a review, and spread it among developers and on social media.
